contracts/checkpointoracle,contracts/checkpointoracle/contract,params/types/genesisT: run 'go generate ./...' with partial success
A few things I learned along the way this evening.

- solc in path must be 0.6.0 or some mysterious upper
bound less than the latest available versions that I
also tried.
- solcjs is not solc. npm install solc installs solcjs
which is like solc but is not solc.

All of this partially fixes an error which looked like this.

go generate ./...
protoc-gen-go: no such flag -import_path
--go_out: protoc-gen-go: Plugin failed with status code 1.
accounts/usbwallet/trezor/trezor.go:45: running 'protoc': exit status 1
Error: Source file requires different compiler version (current compiler is 0.8.5+commit.a4f2e591.Linux.g++) - note that nightly builds are considered to be strictly less than the released version
 --> contract/oracle.sol:1:1:
    |
           1 | pragma solidity ^0.6.0;
         | ^^^^^^^^^^^^^^^^^^^^^^^

              contracts/checkpointoracle/oracle.go:20: running 'solc': exit status 1

The error now looks like this

go generate ./...
protoc-gen-go: no such flag -import_path
--go_out: protoc-gen-go: Plugin failed with status code 1.

Maybe we don't even want these changes. I don't know.
I just want the command to work for the sake of order
in the universe.

But seriously
- maybe we should upgrade the Solidity version pragma too/instead?
- maybe proto-gen-go actually wants a different version than 'latest',
  (which is what 'make devtools' installs).
- maybe we report the issue at ethereum. their trezor.go looks same
  same.

Goodnight, to dream of green lights.

Date: 2022-12-20 19:40:04-08:00
Signed-off-by: meows <b5c6@protonmail.com>